# Site settings
title: Ask Blue Cat
description: MEOW
url: "https://blackspotinmyiiiies.github.io"
baseurl: "/askbluecat.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme (optional - you can change this later)
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
