# Site settings
title: Ask Blue Cat
description: MEOW
url: "https://askbluecat.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme - Architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Force rebuild
