title: AskBlueCat
description: BlueCat's meow-tastic cybersecurity hub, meow!
baseurl: ""
url: "https://askbluecat.com"
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-architect
